### ISSUE TITLE
Activating the VM breaks while trying tou build guest additions.

### ISSUE THREAD

**Issue by MonsieurCellophane** [nasa-gibs/worldview#183]
Using Fedora Core 25/VirtualBox-5.1

'vagrant up'  fails while building the VirtualBox Gues Additions, complaining about being unable to locate kernel headers. Apparent reason is that the running kernel is of a different version of some of the kernel development packages (the lattest being at 3.10.0-514.10.2.el7) Upgrading the kernel and its devel tools to the same version (this requires doing the upgrade, installing grub2-tools - not installed - and use them to change and eventaully erase the older kernels) allows th provisioning to porceed.

(though it later unravels during the npm fase:

       ==> default: npm ERR! Linux 3.10.0-514.10.2.el7.x86_64
       ==> default: npm ERR! argv "/usr/bin/node" "/bin/npm" "install" "--no-bin-links"
       ==> default: npm ERR! node v6.9.4
       ==> default: npm ERR! npm  v3.10.10
       ==> default: npm ERR! Maximum call stack size exceeded
       ==> default: npm ERR! 
       ....
      /vagrant/node_modules/coffee-script/lib/coffee-script/lexer.js:33
            i += this.identifierToken() || this.commentToken() || this.whitespaceToken() || this.lineToken() ||       this.heredocToken() || this.stringToken() || this.numberToken() || t
                                                                                                                                                                                
    SyntaxError: Invalid or unexpected token
        at Object.exports.runInThisContext (vm.js:76:16)
        at Module._compile (module.js:542:28)
        at Object.Module._extensions..js (module.js:579:10)
        at Module.load (module.js:487:32)
        at tryModuleLoad (module.js:446:12)
        at Function.Module._load (module.js:438:3)
        at Module.require (module.js:497:17)
        at require (internal/module.js:20:19)
        at Object.<anonymous> (/vagrant/node_modules/coffee-script/lib/coffee-script/coffee-script.js:10:10)
        at Object.<anonymous> (/vagrant/node_modules/coffee-script/lib/coffee-script/coffee-script.js:167:4)

Cannot say if this is a related or independent issue)

**Comment by Benjaki2** [comment]
See #193
