### ISSUE TITLE
Fix commonly flaky E2E test(s)

### ISSUE THREAD

**Issue by jasontk19** [nasa-gibs/worldview#2355]
**Describe the bug**
There are some E2E tests that are failing somewhat regularly on the OSX/Chrome E2E Travis job that seem fine about half the time, always seem to pass locally, and always seem to pass on the Linux/Firefox E2E Travis job.  We should investigate these and try to get them to pass more consistently since they are often the only thing failing an entire build.

The most common seems to be:
```
✖ data-download/data-download-test
 – No data in view - Zoom out or move map indicator displayed when no data in view (24.41s)
   Expected element <#indicator> to not be visible after 20000ms - expected "not visible" but got: "visible"
       at Object.No data in view - Zoom out or move map indicator displayed when no data in view (/Users/travis/build/nasa-gibs/worldview/e2e/features/data-download/data-download-test.js:111:8)
```

If we see any others frequently, they should be added to this issue.

 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]

**Additional context**

**Comment by Benjaki2** [comment]
Also seeing
```
✖ image-download/formats-test
 – Switch to geographic, select KMZ, switch to arctic, is PNG (16.676s)
   Timed out while waiting for element <.wv-image-button> to be present for 10000 milliseconds. - expected "visible" but got: "not found"
       at clickDownload (/Users/travis/build/nasa-gibs/worldview/e2e/reuseables/image-download.js:20:7)
       at Object.Switch to geographic, select KMZ, switch to arctic, is PNG (/Users/travis/build/nasa-gibs/worldview/e2e/features/image-download/formats-test.js:82:5)
```
