### ISSUE TITLE
Error "no file previewLayerOverrides.json" when previewSnapshots is set to false 

### ISSUE THREAD

**Issue by ZachTRice** [nasa-gibs/worldview#2783]
**Describe the bug**
Worldview fails to build when `"previewSnapshots": false` is set in features.json and there is no `previewLayerOverrides.json` file present.

Get the following errors:
```
Traceback (most recent call last):
  File "tasks/../tasks/python3/fetchPreviewSnapshots.py", line 192, in <module>
    with open(overrides_file, 'rt') as overrides_json:
FileNotFoundError: [Errno 2] No such file or directory: 'tasks/../config/active/common/previewLayerOverrides.json'
```

**To Reproduce**
Build with previewSnapshots: false and no previewLayerOverrides.json

**Expected behavior**
If I set previewSnapshots to false, I should not need to have the previewLayerOverrides.json file

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by ZachTRice** [comment]
Also, when I add the previewLayerOverrides.json file (with `previewSnapshots` still set to `false`), I am required to have `imageDownload` feature enabled.

So, there is essentially no way to disable the imageDownload feature.

Error
```
Traceback (most recent call last):
  File "tasks/../tasks/python3/fetchPreviewSnapshots.py", line 198, in <module>
    snapshots_url = wv_json_dict['features']['imageDownload']['url']
KeyError: 'imageDownload'
```
