### ISSUE TITLE
WV SIT in GIBS environment - Multiple issues

### ISSUE THREAD

**Issue by jejeking** [nasa-gibs/worldview#491]
First issue is when I run "fetch". We unset the proxy to allow fetching of the getCapabilities:

```
[gibs@tools-sit ~]$ cd /usr/share/gibs/ecc/worldview
[gibs@tools-sit worldview]$ unset https_proxy
[gibs@tools-sit worldview]$ unset HTTPS_PROXY
[gibs@tools-sit worldview]$ unset http_proxy
[gibs@tools-sit worldview]$ unset HTTP_PROXY
[gibs@tools-sit worldview]$ cd /usr/share/gibs/ecc/worldview
[gibs@tools-sit worldview]$ /usr/bin/grunt fetch --env sit-ext --force
Running "exec:fetch" (exec) task
>> wv-options-fetch: ERROR: local variable 'ident' referenced before assignment
>> wv-options-fetch: ERROR: local variable 'ident' referenced before assignment
wv-options-fetch: https://sit.gibs.earthdata.nasa.gov/wmts/epsg4326/all/wmts.cgi?request=GetCapabilities
wv-options-fetch: https://sit.gibs.earthdata.nasa.gov/wmts/epsg4326/best/wmts.cgi?request=GetCapabilities
wv-options-fetch: https://sit.gibs.earthdata.nasa.gov/wmts/epsg4326/nrt/wmts.cgi?request=GetCapabilities
wv-options-fetch: https://sit.gibs.earthdata.nasa.gov/wmts/epsg4326/std/wmts.cgi?request=GetCapabilities
```

Next issue is when "config" is ran: We reset the proxies for this part.

```
[gibs@tools-sit worldview]$ set HTTP_PROXY
[gibs@tools-sit worldview]$ set http_proxy
[gibs@tools-sit worldview]$ set HTTPS_PROXY
[gibs@tools-sit worldview]$ set https_proxy
[gibs@tools-sit worldview]$ /usr/bin/grunt config --env sit-ext
Running "remove:build_config" (remove) task
>> 2 paths cleaned.

Running "git-rev-parse:config" (git-rev-parse) task
>> 91ce88

Running "remove:config_src" (remove) task
>> 0 paths cleaned.

Running "exec:config" (exec) task
wv-options-wmts: 0 error(s), 0 warning(s), 2 layers for GIBS:epsg4326:all
wv-options-wmts: 0 error(s), 0 warning(s), 540 layers for GIBS:epsg4326:best
wv-options-wmts: 0 error(s), 0 warning(s), 227 layers for GIBS:epsg4326:nrt
wv-options-wmts: 0 error(s), 0 warning(s), 455 layers for GIBS:epsg4326:std
>> Traceback (most recent call last):
>>   File "bin/../bin/wv-options-wmts", line 232, in <module>
>>     error_count, warning_count, layer_count = process_entry(entry, colormaps)
>>   File "bin/../bin/wv-options-wmts", line 192, in process_entry
>>     id = gc_layer["ows:Identifier"]
>> TypeError: string indices must be integers
>> Exited with code: 1.
Warning: Task "exec:config" failed. Use --force to continue.
```

**Comment by jejeking** [comment]
I have copied this from WV-1824

**Comment by Benjaki2** [comment]
@jejeking Looks like it's an issue with the getCapabilities. A couple of the getCapabilities only show one layer. That causes things to break on our end because python is trying to loop through the layer list.
